### ISSUE TITLE
Mobile LDAP Authentication

### ISSUE THREAD

**Issue by kelsen** [bacularis/bacularis-app#31]
I've installed bacularis today, configured ldap sucessfully and I can login with my active directory login through web browser on pc.
The issue I'm facing is that I was trying bacularis on mobile web and I can't login with the same user.
I've noticed on apache2 access log this line below.
`localhost:80 192.168.20.56 - - [19/Feb/2024:15:03:27 -0300] "GET /panel/config HTTP/1.1" 401 262 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 17_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/121.0.6167.171 Mobile/15E148 Safari/604.1"`

**Comment by kelsen** [comment]
forgive me please I'was accessing the configuration (/panel/config) page instead of login page (/web).
I can authenticate with ldap login now.

**Comment by ganiuszka** [comment]
Hello @kelsen,

Thanks for letting us know that you solved this problem.

Yes, ``/panel/config`` is for API panel while ``/`` or ``/web`` is for the web interface.

When I read your message first time I was thinking that you use a proxy that has a problem with passing some headers, because it could be similar behaviour to this that you experienced :-) I started checking what can be wrong and now I see and I am glad that it was only wrong address.

Thanks.

Best regards,
Marcin Haba (gani)
