### ISSUE TITLE
Network test feature: results not picked up in UI

### ISSUE THREAD

**Issue by nisori** [bacularis/bacularis-app#37]
Hi,

I've just noticed the new Network test feature in the release notes - what a cool feature! However, I've tried it and on my system it doesn't seem to work properly.

The test is triggered, is being performed by Bacula (that is visible in Raw output) but the Bacularis UI doesn't seem to notice that the test is finished. The throbbers (the spilling circles) under the arrows continue to spin and no values are shown (for Packets, Duration, RTT etc.).

Bacula version: 9.6.7

Screenshot:

![Bacularis Screenshot 2024-04-09 125647](https://github.com/bacularis/bacularis-app/assets/90049468/1297e1e5-9a16-4a50-911f-f1b09eca11cc)

**Comment by ganiuszka** [comment]
Hi @nisori,

Thank you for reporting this problem. It happens because on Bacula ``9.6`` the output is slightly different than on ``11.x``, ``13.x`` and ``15.x``.

Fortunately I prepared a fix for that. If you want you can use the attached patch. If you prefer to wait on the next release it is fine as well.

For the patch, it is two lines patch for Bacularis ``2.7.0`` that enables working this network test with Bacula ``9.6`` too. This line with Packets, Duration, RTT...etc. will be not filled because these values are unavailable on Bacula ``9.6``, but all the rest should work well.

[bacularis-web-fix-network-test-bacula-9.6.x.patch.txt](https://github.com/bacularis/bacularis-app/files/14922312/bacularis-web-fix-network-test-bacula-9.6.x.patch.txt)

Thanks!

Best regards,
Marcin Haba (gani)
