### ISSUE TITLE
Feature proposal - email alerting capability

### ISSUE THREAD

**Issue by sitemapxml** [bacularis/bacularis-app#56]
Hello,

So far, the Bacularis provide option to choose between "Standard" and "Daemon" message channels, but no explicit way to configure email alerting and notifications.

I am one of those who use emails extensively for this purpose, so I would really like to see this functionality inside the interface.

Bacula natively provide `bsmtp` program, which can be used for sending emails, although, external SMTP or some different local program like exim or postfix might be also considered, since the bsmtp is quite limited.

Here is the official page about the messages resource:
https://www.bacula.org/15.0.x-manuals/en/main/Messages_Resource.html

I think this might fit nicely on settings page under `General` section, or as a separate tab, like "Alerts" or "Notifications".

Also, it would be nice to have the ability to edit `mailcommand`, and to have some default setting as a starting point.

@ganiuszka I'm curious to hear your thoughts.

**Comment by ganiuszka** [comment]
Hello @sitemapxml

I am glad to let you now that today we released Bacularis ``4.1.0`` that provides the plugin support. One of the new plugins is the e-mail notification plugin that implements your idea about Bacularis e-mail notification. Here you can see the doc and video materials about it:

E-mail notification plugin:
https://www.youtube.com/watch?v=6Y-nQ8ysa10

Documentation for plugins:
https://bacularis.app/doc/plugins/basic.html

Thanks! :smile:

Best regards,
Marcin Haba (gani)

**Comment by ganiuszka** [comment]
Hi @sitemapxml

Thanks for your opinion :smile:  In near feature we plan to extend the plugin interface for new capabilities. In the next release should appear something new in this matter too.

For the question about binary packages, yes, it is true. Since version ``4.0.0`` we changed a way of distributing packages. This ``4.1.0`` is not a major release, so binary packages ``4.1.0`` are not available in those repositories. In ``packages.bacularis.app`` we publish packages for major releases.

Best regards,
Marcin Haba (gani)

**Comment by ganiuszka** [comment]
Hi @sitemapxml

If you are looking for a way with updating Bacularis by one command, then the installation using Composer might be a good way:

https://bacularis.app/doc/brief/installation.html#install-using-composer

For cloning repositories, it isn't easy way of having updateable environment because we have four repositories and one external tar file. You can see how it looks in this manual installation:

https://bacularis.app/doc/brief/installation.html#install-manually

This chapter might be good to read as well:

https://bacularis.app/doc/brief/before-you-start.html#what-installation-method-should-i-use

Best regards,
Marcin Haba (gani)
