### ISSUE TITLE
deployment doesn't work right

### ISSUE THREAD

**Issue by darkfritz2** [bacularis/bacularis-app#63]
Hello,
just seen that the OS Profiles in the Deployment section are not correct anymore. 
For ubuntu 22.04, for example, the client to install bacula-fd is not bacula-fd, but bacula-client (because i've used the newest bacula version maybe ... ?).

Also, there must be some kind of fix on the deployment script because for ubuntu 22.04 bacula has been taken out from the official repo and these commands i have to put into the server so i can make it work:

apt-get install apt-transport-https
wget https://www.bacula.org/downloads/Bacula-4096-Distribution-Verification-key.asc
apt-key add Bacula-4096-Distribution-Verification-key.asc
rm Bacula-4096-Distribution-Verification-key.asc
nano /etc/apt/sources.list.d/bacula.list

deb [arch=amd64] https://www.bacula.org/packages/**somecodefrombacula**/debs/15.0.2 jammy main

kind of hard for non-sysadmins to figure things out if the videos: https://www.youtube.com/watch?v=W-A1S2Yr3a0 show you that it should be actually easy...

**Comment by ganiuszka** [comment]
Hello @darkfritz2,

Thank you for your feedback about the deployment function.

By default Bacularis OS profiles use the system repositories to install the Bacula packages. The system Bacula package names are not compatible with the package names from Bacula.org repositories. If somebody decides to use Bacula.org packages, it requires manual adapting the properties in the OS profiles. In Bacularis version 4.2.0 we extended support for deploying with the Bacula packages from bacula.org by adding a function which automatically fits all paths to the Bacula.org paths. You can see this function on this video:

https://www.youtube.com/watch?v=Q9OGG0cj6zA

For using the Bacula.org repositories on Ubuntu Jammy in the past we recorded a video that shows how to change the OS profile manually for that:

https://www.youtube.com/watch?v=EkSceivoUyc

The Jammy is a specific system because in this Ubuntu version the Bacula packages have been temporary removed from the official system package repositories by the Ubuntu package maintainers. It is the reason why usually people use the Bacula.org packages on Jammy.

But lately it has been changed, because finally Ubuntu made available the system repositories with the Bacula packages for Jammy. They are not in the 'main' section but it requires adding an additional Ubuntu repository. We described all this in the 'Troubleshooting' section in Bacularis documentation here:

https://bacularis.app/doc/brief/troubleshooting.html#error-during-bacula-installation-in-initial-wizard-on-ubuntu-22-04-jammy

I understand that for non-sysadmins in some cases setting it up can be not easy like this installation on the Jammy system. We do our best to make this process as easy as possible, but some things require more time. We are not able to speed it up. Bacula generally is known as very good but not easy software to use and our mission in the Bacularis Project is to make it easier for people.

I encourage to join to the Bacularis user group. There people can ask questions about Bacularis and find help:

https://groups.google.com/g/bacularis

Best regards,
Marcin Haba (gani)

**Comment by darkfritz2** [comment]
Thank you. i figured out the issue for bacula 15 (that everything was moved to /opt/bacula...)
though the deployment in both cases is working now, the client for ubuntu jammy is still not seen. and if i add the client manually then the communication doesnt work.

for almalinux 8 i started the deployment. it installed bacularis and everything need but:
1. if i try to access the panel i get HTTP ERROR 500
2. if i try to install the client on the server i get the error: Problem with connection to remote host. cURL error 0: . 

the almalinux 8 client is new (for testing purposes). the comands used: update, reboot, setenforce 0 (because i think there should be no issues with selinux). no firewall/iptabels is installed. just a new VM for testing...

i tried to configure 'server - remote client' manually but i don't understand how to configure it. neither using the conf files or in bacularis

i think i should move this discussion to the google groups....

**Comment by ganiuszka** [comment]
Hello @darkfritz2,

Great to hear that it started working with Bacula 15 packages.

For the HTTP Error 500 on your AlmaLinux 8, do you think it can be this problem described here?

https://bacularis.app/doc/brief/troubleshooting.html#http-error-500-and-no-interface-page-is-loading

If it is, I think this Troubleshooting section can solve both experienced problems in points 1. and 2.

For continuing on the Bacularis user group, if it is OK for you, we can stay here in GitHub for this topic. For new questions in the future, yes, it might be a good idea to ask them there. Thanks.

Best regards,
Marcin Haba (gani)

**Comment by darkfritz2** [comment]
yes.. that did the trick. finally, the first server as a client :)
