### ISSUE TITLE
sources.list entry misspelt - apt error

### ISSUE THREAD

**Issue by sitemapxml** [bacularis/bacularis-app#65]
Hi,

I am trying to deploy API host on some Debian 12 server, and the deployment is stuck at `Install Bacularis` step.

By inspecting the log, this can be seen at the end:
```
[0mSkipping acquire of configured file 'main/source/Sources' as repository 'https://www.bacula.org/packages/[repo-key]/debs/15.0.2 bookworm InRelease' does not seem to provide it (sources.list entry misspelt?)[0m
Connection to [server] closed.
```
While manually testing, the `apt update` command is working without errors, if the line beginning with `deb-src` inside the `Bacula.list` file is removed.

This is not the first time I noticed this error, but the last time I was too lazy to open an issue, because I managed to find a way to trick the installation process by commenting out the `deb-src` line during the deployment process, so the deployment would be eventually complete.

**Comment by ganiuszka** [comment]
Hi @sitemapxml

Good catch!

Thank you for reporting this issue. Yes, it is a bug in the deployment part.

At the moment I fixed it so since the next release this problem should not happen anymore.

Best regards,
Marcin Haba (gani)

**Comment by ganiuszka** [comment]
Hello @sitemapxml,

Thanks for your detailed report and tests with the deployment function. Let's see what we can fix and improve here.

For the first problem, I tried to reproduce it. I have few questions to you because I was not able to reproduce it with Debian 12.

```
Reading state information... 0%

Reading state information... Done
18 packages can be upgraded. Run 'apt list --upgradable' to see them.
Connection to 10.0.0.201 closed.


EXITCODE=0
quit
```

On my side the process continues and ends successfully. So, I will need your help with some details.

The main question is if below the message about closed connection you have the ``EXITCODE`` line. If yes, could you tell me what is value there?

One more question I have about if in the all the ``apt update`` step you have some not accessible repositories or some errors in the whole apt update output? This deployment function uses exit codes to check the process finished successfully or not. If there is an repository in the system that can cause exiting ``apt update`` with error code != 0 then it can be a problem.

If you run the ``apt update`` command manually in the console. Is the exit code zero? I mean running this after finishing the ``apt`` command:

```
echo $?
```


For the second issue, thanks for the tip with ``--reinstall`` parameter. It sounds useful for this case. It is true that we don't have any function to uninstall the Bacularis and Bacula instances at once and I agree with you that it might be good to have it. I added this task to my Bacularis task list. It seems to be quite important for the deployment function. Thanks.

In your sentences:

```
"I tried to deploy Bacularis once again, but it failed. After that, I tried to clean the environment by removing /etc/bacularis/ directory, but deployment script was complaining about missing files"
```

for me the most important information here is to know what failed at the beginning because rest actions looks to be consequences manual removing the ``/etc/bacularis/`` directory. If this situation with failed deployment will happen again, could I ask you about reporting here the raw output from the deployment window?

This deploy API function was designed in a way that it could be repeated after occurring an error. To see it, after successfully deploying Bacularis API, you can run the ``Deploy`` button once again on the same host. The new process will finish successfully as well. The problem happens in some corner cases for which we count on help of the Community to report them because we are not able to find all of them at once. Many thanks for your help and ideas. With them we are able to see and do much more.

Best regards,
Marcin Haba (gani)

**Comment by ganiuszka** [comment]
Hello @sitemapxml,

Thanks for your report. I appreciate your tests and tries.

For the first error that happens if packages are not upgraded on the system, please let us know if it will be able to reproduce it. I am curious what could happen this wrong behaviour.

For this error:

```
===== Step: Configure Bacularis =====

spawn scp -F /opt/bacularis/protected/Web/Config/ssh.conf -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null /opt/bacularis/protected/Web/Config/api.conf [server]:/tmp/bacularis-deploy/api.conf
Warning: Permanently added '[server]' (ED25519) to the list of known hosts.

api.conf                                        0%    0     0.0KB/s   --:-- ETA
api.conf                                      100% 3960   985.3KB/s   00:00    

EXITCODE=0
quit


spawn ssh -t -F /opt/bacularis/protected/Web/Config/ssh.conf -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null [server] sudo mv /tmp/bacularis-deploy/api.conf /etc/bacularis/API/api.confWarning: Permanently added '[server]' (ED25519) to the list of known hosts.[sudo] password for sudouser:
mv: cannot move '/tmp/bacularis-deploy/api.conf' to '/etc/bacularis/API/api.conf': No such file or directory
Connection to [server] closed.

EXITCODE=1
quit


spawn ssh -t -F /opt/bacularis/protected/Web/Config/ssh.conf -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null [server] sudo chown www-data /etc/bacularis/API/api.confWarning: Permanently added '[server]' (ED25519) to the list of known hosts.[sudo] password for sudouser:
chown: cannot access '/etc/bacularis/API/api.conf': No such file or directory
Connection to [server] closed.

EXITCODE=1
quit
```

The ``Step: Configure Bacularis`` is executed after installing Bacularis by packages on the remote side. In this moment the ``/etc/bacularis/API/`` directory should exist on that remote host. I am sorry if it is obvious question but - did you remove it or it happened automatically without any ingerention?

For this file:

```
/opt/bacularis/protected/Web/Config/bacularis.pub.gpg
```

could you show me the original content of the ``bacularis.pub`` that exists in your system?

This file with the ``.gpg`` extension is created not by Bacularis itself but by the ``gpg`` program when the key is dearmored from the ASCII format. Bacularis does something similar to this:

```
wget https://packages.bacularis.app/bacularis.pub
gpg --dearmor bacularis.pub
```

and the last ``gpg`` command as a result gives ``bacularis.pub.gpg``. Maybe there happened something with the ``bacularis.pub`` that the ``.gpg`` file has not been created.

If you want to have more details from the deployment process, I would propose to enable debug on the Web side. In this debug there are some information not displayed in the raw output console. To do it, please go to the gear wheel icon on the top left side of the web interface. On that page on the ``General`` tab you can use ``Enable debug`` checkbox. After enabling it, in the ``/opt/bacularis/protected/Web/Logs`` you will see files with the debug output. I think it might be useful to look there to see more details.

For this last error with empty raw output console, maybe in the debug will be possible to see something more as well.

Thanks again for your help.

Best regards,
Marcin Haba (gani)

**Comment by ganiuszka** [comment]
Hello @sitemapxml,

Thanks for your response and for providing more details.

For the problem with missing ``/etc/bacularis/`` directory my question was a bit different. It was - what happened that you needed to remove this directory. But for now it is OK, I don't need to understand it deeper. The most important in this case is what you wrote about the ``--reinstall`` parameter, that it fixes manual removing the ``/etc/bacularis/``.

Thanks for providing that ``bacularis.pub`` file. I did a test with ``gpg --dearmor`` command and it created the binary file with ``.gpg`` extension. In this situation I don't know what caused that this ``.gpg`` file was missing that time.

For the debug file I mean ``bacularis-web.log``. It should be created in the ``Logs`` directory and rotated as well. In this file after starting the deployment process you will be able to see messages mainly if some errors will happen. There is also logged all the web interface activity.

For the problem with error on the first ``Add package repository`` step, I am not able to reproduce it but I would like to see what is inside this directory and what permissions it has. Could I ask you about showing me it by the command below?

```
ls -la /tmp/bacularis-deploy/
```

Maybe then I will be able to recreate it and reproduce it on my side.

Thanks for all!

Best regards,
Marcin Haba (gani)

**Comment by ganiuszka** [comment]
Hello @sitemapxml,

Thanks for your time and all explanations.

> There are two interesting things here: first, the file was missing at the time I inspected the /etc directory, and second, after I manually created it, it got removed after I clicked "Deploy" button inside Bacularis, so I think this is the most interesting part. It seems like the Bacularis itself is removing it.

In this step the ``.gpg`` file is created on the local web interface host from ``.pub`` key file. Then it is copied to remote host to temporary location and then it is moved to the destination location in ``/usr/share/keyrings/``. At the end this ``.gpg`` file is removed from the local web interface side. So, it is undrstandable that this ``.gpg`` file is on the web interface host by only a short time. One thing that can be missleading here is that the ``.pub`` file stays on the local host and it is not removed. I think it can be easily fixed. I will try to do something with it.

The debug mode in case deploy process it logs mainly errors. It does not log the whole steps.

For content of the ``/tmp/bacularis-deploy/``, this directory is removed at the end of deployment. This ``api.conf`` looks to be a leftover after some errors but even then it should not block any other new processes or next deployments.

For the ``ls -la`` output and privileges, I don't see anything wrong either.

Also I would like to ask you about telling me how you configured sudo for ``h41test`` user and if it is possible, could you provide output from this command:

```
id h41test
```

Thanks!

Best regards,
Marcin Haba (gani)

**Comment by ganiuszka** [comment]
Hello @sitemapxml,

OK, great. Thanks for the sudo settings.

For this problem with removing ``/etc/bacularis`` the deployment process stops on ``Configure Bacularis`` step because the destination path ``/etc/bacularis`` is missing. It is this error that you shown us already:

```
spawn ssh -t -F /opt/bacularis/protected/Web/Config/ssh.conf -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null [server] sudo mv /tmp/bacularis-deploy/api.conf /etc/bacularis/API/api.confWarning: Permanently added '[server]' (ED25519) to the list of known hosts.[sudo] password for sudouser:
mv: cannot move '/tmp/bacularis-deploy/api.conf' to '/etc/bacularis/API/api.conf': No such file or directory
Connection to [server] closed.

EXITCODE=1
quit


spawn ssh -t -F /opt/bacularis/protected/Web/Config/ssh.conf -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null [server] sudo chown www-data /etc/bacularis/API/api.confWarning: Permanently added '[server]' (ED25519) to the list of known hosts.[sudo] password for sudouser:
chown: cannot access '/etc/bacularis/API/api.conf': No such file or directory
Connection to [server] closed.

EXITCODE=1
quit
```

I am able to reproduce this situation and explain it as well. Normally the deploy Bacularis process installs Bacularis. In this specific situation the deploy Bacularis process does not install it because on the system level Bacularis is already installed:

```
bacularis is already the newest version (4.0.0~bookworm).
bacularis-nginx is already the newest version (4.0.0~bookworm).
0 upgraded, 0 newly installed, 0 to remove and 82 not upgraded.
Connection to 10.0.0.201 closed.
```

So, the removed path ``/etc/bacularis`` is not recreated in this step. In next step there is copying to ``/etc/bacularis`` that fails.

This command ``apt install --reinstall bacularis bacularis-nginx`` will not reinstall Bacularis that is ready to work because after running this command, the ``/etc/bacularis`` is incomplete:

```
find /etc/bacularis -ls
   357248      4 drwxr-xr-x   4 www-data www-data     4096 lis 16 18:14 /etc/bacularis
   357249      4 drwxr-xr-x   2 www-data www-data     4096 lis 16 18:14 /etc/bacularis/API
   357250      4 drwxr-xr-x   2 www-data www-data     4096 lis 16 18:14 /etc/bacularis/Web
```

Normally after successful installation in fresh Bacularis should be files with the default credentials for API and Web parts. In this case they are missing. Your next try to deploying Bacularis was successful because at least ``/etc/bacularis`` was already existing so the configuration files could be copied there and the deployment didn't fail. This ``/etc/bacularis`` is specific directory because it stores configuration that in case binary packages is treated in a bit different way than other files. To fix this situation after removing ``/etc/bacularis`` directly from the command line, to the reinstall command we need to add the ``dpkg`` parameter ``--force-confmiss``:

```
apt install --reinstall -o Dpkg::Options::="--force-confmiss" bacularis bacularis-nginx
```

It will work and fix this situation, but it is something what we can't add to Bacularis OS profiles because it could destroy existing Bacularis configuration, of course.

So, summary for this problem is that we can add ``--reinstall`` option that will fix manually removed files (except config files) and this solution will not solve problem with removing ``/etc/bacularis``. However we can't add ``--force-confmiss`` parameter to Bacularis.

Now, when I am thinking about it, maybe we could add to the deployment window a checkbox with an option like ``Force install`` that user can agree if he/she really wants it. For now I added this idea to my list to not forget it.

I think that we know already everything about all the problems described here. Some of them requires some work. We will see when it could be added.

The only think that I am not able to explain is why on your first deployment process step, it failed. I am not able to reproduce it. Is it reproduceable on your side?

Thanks for all your help. I appreciate your effort to make Bacularis better.

Best regards,
Marcin Haba (gani)

**Comment by ganiuszka** [comment]
Hi @sitemapxml,

I am so sorry for your loss. My heartfelt condolences to you and your family.

Many thanks for your input in this ticket.

Best regards,
Marcin Haba (gani)
