### ISSUE TITLE
Job - Run script on Client not working

### ISSUE THREAD

**Issue by Ando-lm** [bacularis/bacularis-app#9]
Hi, when i edit a job and flag "RunsOnClient" in the Runscript Section, in the bacula-dir.conf the corresponding entry is not written.
This is the slice of script written by Bacularis:

Runscript {
    RunsOnSuccess = no
    FailJobOnError = no
    RunsWhen = "Before"
    Command = "/usr/sbin/bkdbsingoli"
  }

Obviously the script on client don't start and the backup is empty.

If I manually modify the bacula-dir.conf with the following entry the script start.

Runscript {
    **RunsOnClient = Yes**
    RunsWhen = "Before"
    Command = "/usr/sbin/bkdbsingoli"
  }

This is a little bug, but every modify done by web interface delete the "RunsOnClient" entry I made.
I Installed 1.6.0 version of Bacularis

![flag](https://github.com/bacularis/bacularis-app/assets/68462200/a90597eb-2984-42b9-8ba6-1e033aa7c200)
![jobflag](https://github.com/bacularis/bacularis-app/assets/68462200/e716b952-c719-490b-b0c4-8ca63c4bd84f)
![jobok](https://github.com/bacularis/bacularis-app/assets/68462200/3569c6df-9424-49a3-99c6-b299c14c68bc)

**Comment by ganiuszka** [comment]
Hello Ando-lm,

Thank you for your detailed report.

In Bacularis if a Bacula directive stores default value, this directive is not written in the config. It is because the default value works the same way as directive is written in config and when it is not written at all.

For example, if default value for a directive:``AllowFDConnections`` is ``No``, then it will be written to config only when we switch it to ``Yes`` like below:

```
AllowFDConnections = Yes
```

Now let's look at your case. Default value for ``RunsOnClient`` is ``Yes``, as you can see in the red table in Bacula documentation:

https://www.bacula.org/13.0.x-manuals/en/main/Configuring_Director.html#34307

So, ``RunsOnClient`` is written in Bacula config only if it is set to ``No``, so when the checkbox is unchecked.

The last question to answer is - why your backup ``NewAmerigoDB`` does not work after saving by Bacularis. It can be because in the Runscript the ``RunsOnSuccess`` directive is set to ``No``. So, it causes that the command will not be executed for healthy jobs with good jobstatus.

As a solution I would propose to to set runscript in Bacularis like here

```
Runscript {
  RunsWhen = "Before"
  Command = "/usr/sbin/bkdbsingoli"
}
```

It should work on the Bacula Client side and should run on the Client host this command:

```
/usr/sbin/bkdbsingoli
```

I am attaching screenshot here:

![Bacularis-Bacula-Web-Interface-runscript](https://github.com/bacularis/bacularis-app/assets/7281156/ba0b2755-12b8-477d-98ce-0c045b8ba810)

Please let us know it it helped. Thank you in advance for your feedback.

Best regards,
Marcin Haba (gani)

**Comment by Ando-lm** [comment]
ok, it worked. 
Excuse me but I was convinced I had done this test that you proposed to me.
Thanks
